#!/usr/bin/env python3
"""Generates src/creality_k2_materials.h from a Creality K2/CFS
material_database.json snapshot (place one at the project root — see
tag_creality.h for where this file comes from and what it's for).

Re-run this whenever a fresher material_database.json is obtained; the
committed header is otherwise just a point-in-time snapshot, not something
this firmware ever re-fetches on its own.
"""
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SRC_JSON = ROOT / "material_database.json"
OUT_HEADER = ROOT / "src" / "creality_k2_materials.h"


def main():
    with open(SRC_JSON, encoding="utf-8") as f:
        data = json.load(f)

    items = data["result"]["list"]
    seen = {}
    order = []
    for it in items:
        base = it["base"]
        mid = base["id"]
        if mid in seen:
            continue  # keep the first entry seen for a given id (see header comment on why)
        if len(mid) != 5:
            print(f"warning: skipping id of unexpected length: {mid!r}", file=sys.stderr)
            continue
        for field, value in (("id", mid), ("brand", base["brand"]), ("name", base["name"])):
            if '"' in value or "\\" in value:
                print(f"warning: skipping id {mid!r}, unescaped char in {field}: {value!r}", file=sys.stderr)
                break
        else:
            seen[mid] = (base["brand"], base["name"])
            order.append(mid)

    lines = [
        "#pragma once",
        "",
        "// Auto-generated by scripts/gen_creality_k2_materials.py — DO NOT EDIT BY HAND.",
        "// Source: a material_database.json snapshot from the user's own Creality K2",
        "// under /mnt/UDISK/creality/userdata/box/. NOT a complete or",
        "// permanent list — this is whatever Creality's cloud material catalog",
        "// happened to contain on that one device on that one date; Creality can and",
        "// does add new materials over time. An id with no entry here falls back to a",
        "// raw \"Material <id>\" display rather than failing.",
        "//",
        "// Regenerate: drop a fresh material_database.json into the project root and",
        "// re-run this script.",
        "",
        "struct CrealityK2Material {",
        "    const char *id;",
        "    const char *brand;",
        "    const char *name;",
        "};",
        "",
        "static const CrealityK2Material CREALITY_K2_MATERIALS[] = {",
    ]
    for mid in order:
        brand, name = seen[mid]
        lines.append(f'    {{"{mid}", "{brand}", "{name}"}},')
    lines.append("};")
    lines.append(
        "static const int CREALITY_K2_MATERIAL_COUNT = "
        "sizeof(CREALITY_K2_MATERIALS) / sizeof(CREALITY_K2_MATERIALS[0]);"
    )
    lines.append("")

    OUT_HEADER.write_text("\n".join(lines), encoding="utf-8")
    print(f"Wrote {len(order)} materials to {OUT_HEADER}")


if __name__ == "__main__":
    main()
