#pragma once

// German-only UI strings — this is an internal Product-Manager/Admin tool,
// unlike esp32rental's member-facing terminal, so no runtime EN/DE toggle is
// needed here (see esp32rental/src/i18n.h for that pattern if this ever
// becomes member-facing). Proper umlauts, rendered via the custom
// extended-Latin fonts generated by scripts/gen_fonts.sh (see lv_conf.h) —
// LVGL's built-in fonts only cover 0x20-0x7F, no umlauts at all.

// App chrome — the top-bar title (ui.cpp) and the boot screen (main.cpp,
// drawn directly via LovyanGFX before LVGL is even initialized) show the
// same name; a single constant means the two can't drift apart.
#define STR_APP_TITLE        "Filament-Station"
#define STR_BOOTING          "wird gestartet..."
#define STR_OTA_UPDATE_FMT   "OTA Update: %d%%"

#define STR_WAITING          "Bereit - Spule scannen"
#define STR_READING          "Lese Tag..."
#define STR_CONNECTING       "Verbinde mit WLAN..."
#define STR_NO_CONNECTION    "Keine Verbindung"

#define STR_CHECKED_IN       "Eingebucht"
#define STR_CHECKED_OUT      "Ausgebucht"

#define STR_UNKNOWN_TAG      "Unbekanntes Tag-Format"
#define STR_UNKNOWN_TAG_HINT "Bitte im Web-Interface manuell erfassen"

#define STR_LABEL_BRAND      "Marke"
#define STR_LABEL_TYPE       "Typ"
#define STR_LABEL_COLOR      "Farbe"
#define STR_LABEL_WEIGHT     "Gewicht"
#define STR_LABEL_SERIAL     "Seriennummer"
#define STR_LABEL_STOCK      "Im Bestand"
#define STR_YES              "Ja"
#define STR_NO               "Nein"

#define STR_PICK_WEIGHT      "Gewicht nicht auf Tag"
#define STR_PICK_WEIGHT_SUB  "Bitte wählen:"

#define STR_BTN_CHECKIN      "Einbuchen"
#define STR_BTN_CHECKOUT     "Ausbuchen"
// Shown (with a spinner, see enter_processing() in ui.cpp) while the
// blocking checkin/checkout API call is in flight — distinct wording from
// the button labels above so this screen reads as "in progress", not as a
// static repeat of what was just tapped.
#define STR_BOOKING_CHECKIN  "Wird eingebucht..."
#define STR_BOOKING_CHECKOUT "Wird ausgebucht..."

#define STR_ERROR_GENERIC    "Fehler"

// ── Test-tag wizard ("Programmieren") ────────────────────────────────────────
// Writes a freshly generated test tag in one of the four supported formats —
// see README.md's "Testtags programmieren" section. Purely a provisioning
// tool: no MakerSpaceAPI calls are made anywhere in this flow.

#define STR_PROG_ENTER_BTN         "Programmieren"
#define STR_PROG_PICK_FORMAT       "Tag-Art wählen"
#define STR_PROG_PICK_BASE_MATERIAL "Material wählen"
#define STR_PROG_PICK_MODIFIER     "Variante wählen"
#define STR_PROG_PICK_COLOR        "Farbe wählen"
#define STR_PROG_PICK_BRAND        "Hersteller wählen"
#define STR_PROG_PICK_WEIGHT       "Gewicht wählen"
#define STR_PROG_CONFIRM_TITLE     "Bereit zum Schreiben"
#define STR_PROG_NO_SERIAL_NOTE    "Kein Seriennummer-Feld"
#define STR_PROG_WRITE_A        "Ersten Tag auflegen\n(Seite A der Spule)"
#define STR_PROG_WRITE_B        "Zweiten Tag auflegen\n(Seite B der Spule)"
#define STR_PROG_WRITING        "Schreibe Tag..."
#define STR_PROG_DONE           "Beide Tags beschrieben!"
#define STR_PROG_ALREADY_TITLE  "Tag ist nicht leer"
// Deliberately short — with a dedicated Überschreiben button right below
// this hint, it only needs to name the alternative (a different, genuinely
// blank tag), and short enough to reliably stay on one line at
// 304px/MY_FONT_14 without overlapping prog_overwrite_btn below it.
#define STR_PROG_ALREADY_HINT   "Oder anderen Tag auflegen"

#define STR_BTN_WRITE       "Schreiben"
#define STR_BTN_CANCEL      "Abbrechen"
#define STR_BTN_RETRY       "Erneut versuchen"
// Deliberately forces an overwrite of a tag this wizard already recognizes
// as some known format — e.g. transferring an already-programmed tag from
// one spool onto another with different filament. See
// nfc_arm_write()/handle_write_request()'s own comments in nfc_reader.h/.cpp
// for why this is a separate, explicit opt-in rather than the default.
#define STR_BTN_OVERWRITE   "Überschreiben"

// ── Write-path error messages (nfc_reader.cpp / tag_*.cpp) ──────────────────
// Previously hardcoded directly in each tag_*.cpp/nfc_reader.cpp as raw
// string literals, several with ASCII "ue"/"oe"/"gross" substitutes instead
// of real ü/ö/ß — an old habit that predates this project's umlaut-capable
// extended font (see the top of this file) and, worse, meant these strings
// weren't in the one place a future translation would look. Moved here
// (still German-only, like everything else in this file) so both problems
// are fixed at once; %u-parameterized ones stay as snprintf() format
// strings at their call sites, same as before.
#define STR_ERR_UNKNOWN_TARGET_FORMAT      "Unbekanntes Zielformat"
#define STR_ERR_VERIFY_MISMATCH            "Geschrieben, aber Kontroll-Lesevorgang stimmt nicht überein"

#define STR_ERR_JSON_TOO_LARGE             "JSON zu groß"
#define STR_ERR_NDEF_WRITE_FAILED_OPENSPOOL "NDEF-Schreiben fehlgeschlagen - Tag beschreibbar (NTAG215/216)?"
#define STR_ERR_NDEF_WRITE_FAILED_OPENTAG3D "NDEF-Schreiben fehlgeschlagen - Tag zu klein (NTAG215/216 nötig) oder nicht beschreibbar?"

#define STR_ERR_BLOCK_NOT_WRITABLE_FMT     "Tag nicht beschreibbar (Block %u) - ist er wirklich leer?"
#define STR_ERR_WRITE_FAILED_BLOCK5        "Schreiben fehlgeschlagen (Block 5)"
#define STR_ERR_WRITE_FAILED_BLOCK9        "Schreiben fehlgeschlagen (Block 9)"
#define STR_ERR_SECTOR_LOCK_FAILED_FMT     "Sperren von Sektor %u fehlgeschlagen - Daten stehen, Tag bleibt unversperrt"
