#pragma once
#include <Adafruit_PN532.h>
#include "tag_types.h"

// Creality RFID tags: MIFARE Classic 1K, sector 1 (blocks 4-6). Two genuinely
// different documented layouts exist, from two independent sources, and this
// firmware tries BOTH (see tag_parse_creality()'s own comments for the exact
// order and why it's safe) rather than picking one — both plausibility
// checks are specific enough not to collide, and real spools have been found
// in both layouts.
//
// 1) The "old" layout, plaintext ASCII, authenticated with the MIFARE
//    default key (0xFFFFFFFFFFFF) — per Bambu-Research-Group/RFID-Tag-Guide's
//    CrealityRfid.md, itself sourced from community reverse-engineering.
//    Confidence: low-medium — even that doc's own authors weren't certain
//    about several fields (see "Spool ID" below), and newer Creality tags
//    are reportedly AES-encrypted, which this layout doesn't cover at all
//    (see (2)).
//
//    It also carries a 4-hex-digit "Supplier" field (SUPPLIER_POS/
//    SUPPLIER_LEN in tag_creality.cpp). It reportedly distinguishes
//    something like Generic/Creality/eSun-branded spools, but no source
//    documenting the actual hex-code-to-name mapping has been found.
//    tag_parse_creality() does NOT attempt to decode it for this reason —
//    inventing a mapping and presenting it as a real brand would risk
//    mislabeling a spool with more confidence than the data supports (same
//    reasoning as "Spool ID" below). tag_write_creality() writes a fixed
//    placeholder into it for the same reason: there's nothing real to write
//    yet. Revisit once the real encoding is confirmed.
//
// 2) The "K2/CFS" layout, from DnG-Crafts/K2-RFID — an independent,
//    considerably more detailed reverse-engineering effort (Android app +
//    Arduino ESP32/ESP8266/Pico firmware + Windows app, all embedding
//    byte-identical constants) apparently targeting Creality's newer
//    K2-printer/CFS multi-material system. Confidence: medium-high —
//    confirmed against three real spools (two factory-original Creality
//    tags plus one written with the third-party DnG-Crafts Android app for
//    a Generic PLA spool that came with no factory tag at all, and read back
//    correctly by a real Creality K2 Plus printer): material id, color, and
//    weight all decoded to exactly the right values in every case, strong
//    validation of the byte layout itself.
//
//    That real-spool testing also narrowed the signature check considerably
//    from what DnG-Crafts' own demo string implied. See tag_creality.cpp's
//    CrealityK2 namespace and looks_like_k2_data() for exactly what's
//    checked now (only position 17's fixed '0' marker, plus content-shape
//    checks on the fields this code actually decodes) and why that's still
//    safe — the derived-key authentication that has to succeed before this
//    check even runs is itself a strong filter against an unrelated card
//    matching by coincidence. The "reserved" tail (see PLAUSIBLE_CHECK_LEN)
//    is not reliably all-zero on a real tag and isn't validated. The vendor
//    field may track the written material's own brand (Creality vs.
//    Generic) rather than being a fixed constant — plausible from the one
//    Generic-written sample, but not hardcoded as a second confirmed mapping
//    (see VENDOR_POS's own comment).
//
//    Genuinely unclear whether this layout describes the same tag
//    generation as (1), a strictly newer one, or a K2/CFS-specific variant
//    that coexists with (1) on other printers. Two sub-variants, both
//    handled:
//      - plain (default key, like (1))
//      - AES-encrypted: this tag's own sector-1 key is derived from its UID
//        via AES-128-ECB with a fixed embedded key, and the block data
//        itself is then also AES-128-ECB-encrypted with a second fixed
//        embedded key — see the CrealityK2 namespace in tag_creality.cpp for
//        both key values and exactly how they're used. Both keys are
//        published in plaintext in the source above; this isn't a secret
//        being protected, just an interoperability detail.
//    The material field is a lookup key into Creality's own (large,
//    cloud-hosted) material database — `creality_k2_materials.h`
//    (auto-generated by `scripts/gen_creality_k2_materials.py` from a
//    material_database.json snapshot — see its own header comment) embeds a
//    name+brand lookup table (Generic/Creality/eSUN/Polymaker); this is a
//    snapshot, not a live lookup, and an id with no table entry falls back
//    to the sector's own 4-digit vendor code for a brand guess (only "0276"
//    is confirmed = Creality; anything else is shown honestly as
//    "Creality (Vendor <code>)" rather than guessed) and a raw
//    "Material <id>" display. The length/weight field is a separate,
//    genuine, small, confirmed 5-value lookup table (see
//    k2_length_code_to_grams()) — unlike (1), which has no weight field at
//    all.
//
// Both layouts' own "Spool ID"/serial fields are deliberately NOT used as
// vendor_serial: for (1), even the original researchers marked it
// "Spool ID...?" (uncertain whether it's genuinely unique per spool or a
// shared batch code); for (2), it's a real per-write field but from
// unofficial, third-party reverse-engineering with no confirmation it's
// guaranteed unique per *physical* spool — confirmed directly: two
// different real factory-original spools carried the identical on-tag
// serial, and neither matched its own printed label serial either. Trusting
// either for the automatic /filament/scan check-in/check-out path risks
// silently treating two different physical spools as the same one. Creality
// tags of either layout therefore always go through the manual
// Einbuchen/Ausbuchen choice, same as any tag with no serial at all.
bool tag_parse_creality(Adafruit_PN532 &nfc, const uint8_t *uid, uint8_t uid_len, FilamentTagData &out);

// Writes a test tag in the K2/CFS *plain* (unencrypted) layout above, not
// the "old" one — chosen specifically so `in.brand` has somewhere real to
// go: the K2 layout's material_id is the only field either layout has that
// fill_from_k2() actually resolves into a brand (via
// creality_k2_materials.h's real Generic/Creality/eSUN/Polymaker data), so
// this is the only layout where writing a chosen brand has any visible
// effect on read-back at all — the old layout's own SUPPLIER field has no
// confirmed real-world meaning and fill_from_old() always reports
// "Creality" regardless of what's written there (see CrealityOld's own
// comment). `in.brand`/`in.type_name`/`in.color` (must be "#RRGGBB") drive a
// real material lookup (find_k2_material_for_wizard() in tag_creality.cpp);
// `in.weight_grams` maps to one of the format's five known length codes.
// Position 17's '0' marker is written (the one byte confirmed fixed across
// every real sample) but no other signature bytes are invented — see
// looks_like_k2_data()'s own comment for why that's still safe to accept on
// read-back.
//
// ALWAYS writes AES-encrypted data (see tag_creality.cpp's own extensive
// comment on this function) and always ends with the sector locked to the
// UID-derived key, mirroring the reference DnG-Crafts/K2-RFID Android app's
// own WriteTag()/CheckTag() exactly: that app's "encrypted" flag only tracks
// the SECTOR KEY (default vs. already-changed), never whether the data
// itself is encrypted — it always is. On a genuinely blank card, it
// authenticates with the plain MIFARE default key, writes the encrypted
// data, and then relocks the trailer to the derived key — a real tag from
// this ecosystem is never left on the default key after its first write.
// When the default key doesn't authenticate at all (already K2-ENCRYPTED,
// e.g. real factory data or an earlier Überschreiben), it falls back to the
// derived key directly, with no relock needed since that key is already
// correct. A card that authenticates with NEITHER key (a real,
// differently-keyed tag this firmware has no key for at all) still fails
// cleanly.
bool tag_write_creality(Adafruit_PN532 &nfc, const uint8_t *uid, uint8_t uid_len, const FilamentTagData &in,
                         char *err, size_t err_cap);
